// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaXZxtVky7RYckpLP_cDTTywiFW2Gj4vY',
    appId: '1:790229041704:web:a346a43aebd65dc0d86b1d',
    messagingSenderId: '790229041704',
    projectId: 'pick-up-5b093',
    authDomain: 'pick-up-5b093.firebaseapp.com',
    storageBucket: 'pick-up-5b093.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOYkL5ozO8OBC3bIdJDFCSzIqn2CO3WlU',
    appId: '1:790229041704:android:abfcfce8d8afa4ffd86b1d',
    messagingSenderId: '790229041704',
    projectId: 'pick-up-5b093',
    storageBucket: 'pick-up-5b093.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKNl8feHQ3bADRA5IEndT8k8h4bNG0oNw',
    appId: '1:790229041704:ios:3ff4e524a9f1922cd86b1d',
    messagingSenderId: '790229041704',
    projectId: 'pick-up-5b093',
    storageBucket: 'pick-up-5b093.appspot.com',
    iosBundleId: 'com.example.basic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKNl8feHQ3bADRA5IEndT8k8h4bNG0oNw',
    appId: '1:790229041704:ios:68f22194a4b18ff3d86b1d',
    messagingSenderId: '790229041704',
    projectId: 'pick-up-5b093',
    storageBucket: 'pick-up-5b093.appspot.com',
    iosBundleId: 'com.example.basic.RunnerTests',
  );
}
